### ISSUE TITLE
AttributeError: 'HaBleakClientWithServiceCache' object has no attribute 'get_services'

### ISSUE THREAD

**Issue by spac3** [TheMicDiet/chihiros-led-control#86]
### Description

The integration fails when attempting to control a Chihiros BLE light (turn on/off, set brightness) in recent versions of Home Assistant. The root cause is a call to `await client.get_services()` in `base_device.py`, which no longer exists in the bleak API used by Home Assistant's BLE stack.

### Environment

- **Home Assistant version:** 2025.x+ (using bleak 0.20+)
- **Integration version:** latest from main
- **Device:** Chihiros BLE LED light

### Error Log

```
Logger: homeassistant.helpers.script.websocket_api_script
Source: helpers/script.py:524

websocket_api script: Error executing script. Unexpected error for call_service at pos 1:
'HaBleakClientWithServiceCache' object has no attribute 'get_services'

Traceback (most recent call last):
  ...
  File "/config/custom_components/chihiros/chihiros_led_control/device/base_device.py", line 403, in _ensure_connected
    resolved = self._resolve_characteristics(await client.get_services())
                                                   ^^^^^^^^^^^^^^^^^^^
AttributeError: 'HaBleakClientWithServiceCache' object has no attribute 'get_services'
```

### Root Cause

bleak 0.20+ removed the async `get_services()` method. BLE services are now automatically discovered during `connect()` and exposed via the synchronous `client.services` property. Home Assistant's `HaBleakClientWithServiceCache` wrapper follows this newer API and does not have `get_services()`.

### Suggested Fix

In `chihiros_led_control/device/base_device.py` around line 403, replace:

```python
resolved = self._resolve_characteristics(await client.get_services())
```

with:

```python
resolved = self._resolve_characteristics(client.services)
```

### Steps to Reproduce

1. Install the Chihiros custom component via HACS or manually
2. Add a Chihiros BLE light device
3. Attempt to turn the light on or off via the HA UI or a service call
4. Observe the `AttributeError` in the logs

**Comment by spac3** [comment]
I have tested the above fix locally and it does work for me on the Chihiros WRGB II slim.

**Comment by TheMicDiet** [comment]
Hi @spac3, the code actually accounts for both new and old version of HA by first trying the new way with the `client.services` and if this doesn't work, it falls back to the old way by calling `client.get_services()`. For me, it works fine with HA 2026.1.
